# Generated by Django 3.1.5 on 2021-01-26 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='fecha_de_creacion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='fecha_de_publicacion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
